### ISSUE TITLE
Low contrast ratio according to WCAG

### ISSUE THREAD

**Issue by marthee** [myth/coroner#1]
Given your background color: `#111111`

**Content colors not passing WCAG AA or WCAG AAA:**
Foreground `#666666` - dark grey text, e.g. date on top and text/numbers in graph
Foreground `#716317` - yellow in graph
Foreground `#174871` - blue in graph
Foreground `#711717` - red in graph
Foreground `#6d2f13` - orange in graph
Foreground `#427117` - green in graph
Foreground `#4c1571` - purple in graph

**Content colors not passing WCAG AAA:**
Foreground `#5f9ea0` - light blue text, `cadetblue`
Foreground `#b8924b` - orange text, `rgb(184, 146, 75)`

**Comment by myth** [comment]
WCAG 2.1 AA SC 1.4.3 Test for Color Contrast

> Congratulations!
> No automated color contrast issues found on the webpage tested
